version: 0.2

phases:
  install:
    commands:
      - echo Installing NGINX -echo apt-get install NGINX
      - sudo apt-get update
      - sudo apt-get install nginx -y
  build:
    commands:
      - echo Build started on date
      - cp index.html /var/www/html
  Post build:
    Commands:
      -echo configuring NGINX
artifacts:
  files:
    -/var/www/html/index.html